### ISSUE TITLE
Improve comfort selection and solve rating volatility

### ISSUE THREAD

**Issue by malfple** [malfple/keyboard-layout-battles#15]
A lot of pairs actually have similar comfort levels, so there should be a third option, or maybe provide a slider

**Comment by malfple** [comment]
In addition, maybe increase the threshold between speed times so that there are more draws (very close scores are sometimes not accurate)

**Comment by malfple** [comment]
Add info to pause after every space to re-memorize the movement. It is better to make mistake than type slow
Add info in battle history page for the scores, currently it's not very user-presentable
Can increase number of word pairs and decrease repetition

**Comment by malfple** [comment]
Add marquee in battle page
- Timer only runs after you press the first letter and until you hit the spacebar!
- Pause after every spacebar and think about the finger movement!
- Picked the wrong word? Just refresh the page!
- Mistakes will reset the timer!
- Just for this test, making mistakes is better than typing slow!
- Take your time thinking about which keys to press before every word!

**Comment by malfple** [comment]
Set glicko c constant to a low number

**Comment by semilin** [comment]
How are speed wins calculated currently? If outliers aren't accounted for they should be. I'd suggest either using the median or doing a trimmed mean.

**Comment by malfple** [comment]
@semilin it is currently taking the sum of the 3 fastest times out of 9
I'm thinking of just taking the fastest now. I'm against taking the median and removing outliers because it makes familiar translations to have even a higher advantage over awkward translations.

**Comment by semilin** [comment]
Okay, I think that makes more sense than median. I'm in favor of just taking the fastest speed.
