### ISSUE TITLE
Always "felt the same" 

### ISSUE THREAD

**Issue by PaulMorris** [malfple/keyboard-layout-battles#20]
I just played two battles and in both of them I chose one layout or the other but they all ended up being "felt the same".

I did click "felt the same" on one of the words in the first battle (but not all of them), and I didn't select "felt the same" at all in the second battle.

This was on Firefox 124.0.1 (64-bit) if that helps.

![Screenshot 2024-03-27 at 15 59 11](https://github.com/malfple/keyboard-layout-battles/assets/1091693/c48e96df-9f59-42a2-8b9a-64daf84af0c8)

**Comment by malfple** [comment]
Found cause: the state `selected` is updated on keypress but not on mouse on:click. The bug is only reproducible if mouse is used to select the comfort picks and no issue found when using keyboard
