### ISSUE TITLE
Input keyboard layout with more keys

### ISSUE THREAD

**Issue by rdavison** [malfple/keyboard-layout-battles#21]
![Screenshot 2024-03-27 at 5 30 39 PM](https://github.com/malfple/keyboard-layout-battles/assets/630055/1ea22e86-565e-407b-be78-d5408c237333)

This is the layout I'm maining minus the letter X because the X goes above Q... but there's no place for it :despair:

**Comment by malfple** [comment]
Fix: do not check required keys on base layout

**Comment by malfple** [comment]
@rdavison fixed
